[package]
name = "tokio01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.20"
base64 = "0.13.0"
tokio = {version = "1.13", features = ["rt", "sync", "rt-multi-thread"]}